### PR TITLE
chore fix: Reworked infrastructure for shelling out, prevent quoting issues

### LINKED ISSUE #503: Issues getting started with epinio on a windows machine
Hi, 

I am trying to get epinio sample application push working on my windows laptop, and ran into issues. Here are are steps I followed.

1. Start with a fresh Rancher Desktop installation. Install epinio prerequisites (kubectl, helm). 

```
c:\2021\Guna\SUSE\epinio\assets>kubectl get nodes
NAME              STATUS   ROLES                          AGE   VERSION
desktop-hiq5d5u   Ready    builder,control-plane,master   68m   v1.21.0+k3s1

c:\2021\Guna\SUSE\epinio\assets>kubectl get ns
NAME              STATUS   AGE
kube-system       Active   70m
default           Active   70m
kube-public       Active   70m
kube-node-lease   Active   70m
kube-image        Active   69m

```

2. Install epinio using `epinio install --verbosity=1`

```
c:\2021\Guna\SUSE\epinio\assets>epinio install --verbosity=1

←[34m🚢 Epinio installing...
←[0m
Configuration...
  🧭  skip-traefik: ←[35mfalse←[0m
  🧭  skip-linkerd: ←[35mfalse←[0m
  🧭  system_domain: ←[32m←[0m
  🧭  email_address: ←[32mepinio@suse.com←[0m
  🧭  user: ←[32m80eab6de208b75a2←[0m
  🧭  password: ←[32m5d53fd58eaf9f17a←[0m

←[34m🚢 Deploying Linkerd...
←[0m
←[32m✔️  Linkerd deployed
←[0m
←[33m⚠️  Traefik Ingress already installed, skipping
←[0m
🕞  Waiting for LoadBalancer IP on traefik service. ←[35m.←[0m

←[32m✔️  Created system_domain: 192.168.46.233.omg.howdoi.website
←[0m
←[34m🚢 Deploying Epinio...
←[0m

←[34m🚢 Deploying Quarks...
←[0m
←[34m🚢 Deploying Tekton...
←[0m←[34m🚢 Deploying ServiceCatalog...
←[0m
←[34m🚢 Deploying CertManager...
←[0m
←[34m🚢 Deploying Gitea...
←[0m
←[34m🚢 Deploying Registry...
←[0mI0617 11:28:37.158803   13904 request.go:655] Throttling request took 1.0333661s, request: POST:https://192.168.46.233:6443/api/v1/namespaces

🕞  Creating name=quarks-secret in quarks ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m
🕞  Waiting for namespace tekton-staging to be appear ←[35m.←[0m
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m
🕞  Creating app=tekton-pipelines-webhook in tekton ←[35m.←[0m

🕞  Starting app=tekton-pipelines-webhook in tekton ←[35m.←[0m

🕞    Starting pod tekton-pipelines-webhook-75d465b94f-vpp7b in tekton ←[35m.←[0m
🕞  Creating app.kubernetes.io/name=webhook in cert-manager ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m
🕞  Creating name=quarks-secret in quarks ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m



🕞  Starting name=quarks-secret in quarks 🕞  Starting name=quarks-secret in quarks ←[35m.←[0m←[35m.←[0m

🕞    Starting pod quarks-secret-599fd66d8d-n4tvw in quarks ←[35m.←[0m←[35m.←[0m

🕞    Starting pod quarks-secret-599fd66d8d-n4tvw in quarks
🕞  Creating app.kubernetes.io/name=memcached in gitea ←[35m.←[0m←[35m.←[0m←[35m.←[0m
🕞  Creating app=service-catalog-catalog-controller-manager in service-catalog ←[35m.←[0m

🕞  Starting app=service-catalog-catalog-controller-manager in service-catalog ←[35m.←[0m←[35m.←[0m←[35m.←[0m

🕞    Starting pod service-catalog-catalog-controller-manager-779dd58cd8-d8g79 in service-catalog ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m

🕞  Starting app.kubernetes.io/name=memcached in gitea ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m

🕞    Starting pod gitea-memcached-c8547c9c9-8tnfp in gitea ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m

🕞  Starting app.kubernetes.io/name=webhook in cert-manager ←[35m.←[0m←[35m.←[0m

🕞    Starting pod cert-manager-webhook-c45b7ff-j68xz in cert-manager ←[35m.←[0m←[35m.←[0m
🕞  Creating app.kubernetes.io/name=webhook in cert-manager ←[35m.←[0m←[35m.←[0m

🕞  Starting app.kubernetes.io/name=webhook in cert-manager ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m

🕞    Starting pod cert-manager-webhook-c45b7ff-j68xz in cert-manager ←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:29:40.395492   13904 request.go:655] Throttling request took 1.1498998s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-n4tvw
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:29:51.183668   13904 request.go:655] Throttling request took 1.0051052s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-779dd58cd8-d8g79
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:30:01.381449   13904 request.go:655] Throttling request took 1.1079966s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-n4tvw
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:30:13.193189   13904 request.go:655] Throttling request took 1.0181201s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-779dd58cd8-d8g79
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:30:32.273127   13904 request.go:655] Throttling request took 1.0201017s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-n4tvw
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:30:47.248971   13904 request.go:655] Throttling request took 1.0023178s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-n4tvw
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:30:58.244605   13904 request.go:655] Throttling request took 1.0024468s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-n4tvw
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:31:32.187162   13904 request.go:655] Throttling request took 1.0095115s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-779dd58cd8-d8g79
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:31:49.185561   13904 request.go:655] Throttling request took 1.0191211s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-779dd58cd8-d8g79
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:32:29.180221   13904 request.go:655] Throttling request took 1.0074101s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-779dd58cd8-d8g79
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mI0617 11:32:40.384614   13904 request.go:655] Throttling request took 1.1380143s, request: GET:https://192.168.46.233:6443/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-n4tvw
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m

←[32m✔️  Quarks deployed
←[0m
←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0m←[35m.←[0mpanic: Deployment epinio-registry failed with error: Failed installing Registry: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.stringData.htpasswd



goroutine 41 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc0004ccde0, 0x246b970, 0xc0002a78b0, 0x24719d0, 0xc0005122b0, 0xc000512270)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:159 +0x217
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:156 +0xdc5

```

3. Clone epinio repository and run push command to push the sample application. This is where I run to an error and stuck.

```
c:\2021\Guna\SUSE\epinio\assets>epinio push sample sample-app --skip-ssl-verification
error initializing cli: failed to resolve epinio api host: epinio api ingress not found
```

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fixes #503

### Description

Portability work induced by trialing installing Epinio on Windows.

The main issue found so far is our use of the `kexec.CommandString()` for shelling out to external commands.
Per the documentation that indirects through `bash -c` and `cmd /c` on Linux and Windows, respectively.
Some of the invoked commands come with their own quotes, both `'` and `"` however, and at least on Windows this causes garbage in the final command to be run. :boom: 

This PR rewrites the foundational code to use the `Command()` function instead, which takes a `...string` argument.
The affected functions (see below for the list) now also take such an argument.
To make that work the arguments got reordered also.
This in turn required rewriting all their callers.

While the conversion was quite mechanical (but not enough to allow search and replace) the tediousness of it may have created typos and such which slipped through the basic check (IOW the code here does compile at least).

Oh, yes, as this was part of the investigation of the issues with installation on Windows the cert manager and registry deployments got extended tracing of their operation also.

### Functions, and notes

  - `helpers.RunProc`,
  - `helpers.KubeCtl`,
  - `proc.Run`, and
  - `machine.Epinio`

The last two are in the test suite helpers.

Note on calling the modified function `helpers.RunProc` (shorthand: `RP`). Similarly for the others

You can call it in one of three ways:

  - `RP(dir, toStdout, "app", "push", more, fixed, strings, ...)`

  - `RP(dir, toStdout, "app", words...)` where `words` is a `[]string{}` slice.

  - `RP(dir, toStdout, "app", append([]string{fixed, strings, ...}, words...)...)`

    This is the form needed when trying to mix fixed strings with variadics from a slice, for the args argument.
    You __cannot__ write

    `RP(dir, toStdout, "app", fixed, strings, words...)`.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
State of the CI testing -  `acceptance-cli` looks to have only two failures left:

  - something in deploying wordpress ... (Possibly in `AppUrl()` helper)
  - log following (No logs retrieved by curl ?)

**Comment by andreas-kupries** [comment]
Fixed log issue. Rebased, resolved conflicts. Collapsed fix it history.

File: deployments/registry.go [hunk 1]
```diff
@@ -129,44 +132,64 @@ func (k Registry) apply(ctx context.Context, c *kubernetes.Cluster, ui *termui.U
...
-		RegistryDeploymentID,
-		tarPath)
-	if out, err := helpers.RunProc(helmCmd, currentdir, k.Debug); err != nil {
+
+	helmArgs = append(helmArgs, action, RegistryDeploymentID)
+	helmArgs = append(helmArgs, `--namespace`, RegistryDeploymentID)
+	helmArgs = append(helmArgs, tarPath)
+	helmArgs = append(helmArgs, `--set`, `auth.htpasswd=`+htpasswd)
+	helmArgs = append(helmArgs, `--set`, fmt.Sprintf("domain=%s.%s", RegistryDeploymentID, domain))
+	helmArgs = append(helmArgs, `--set`, fmt.Sprintf(`createNodePort=%v`, options.GetBoolNG("use-internal-registry-node-port")))
```
Comment (manno) [inline deployments/registry.go:168]: This is the second time I see this, couldn't this  just be an array assignment?

`args := []string{"helm", "--set", "...", "--set", ...}`

Anyhow, not important.

File: deployments/registry.go [hunk 2]
```diff
@@ -194,9 +217,13 @@ func (k Registry) apply(ctx context.Context, c *kubernetes.Cluster, ui *termui.U
 	}
 
 	// Wait for the cert manager to be present and active. It is required
+	log.Info("waiting for cert manager to be present and active")
```
Comment (manno) [inline deployments/registry.go:220]: I was wondering about the missing logger in those deployments 👍

File: acceptance/api/v1/applications_test.go [hunk 3]
```diff
@@ -122,7 +122,10 @@ var _ = Describe("Apps API Application Endpoints", func() {
 
 	waitForPipeline := func(stageID string) {
 		Eventually(func() string {
-			out, err := helpers.Kubectl(fmt.Sprintf("-n %s get pipelinerun %s  -o jsonpath='{.status.conditions[0].status}'", deployments.TektonStagingNamespace, stageID))
+			out, err := helpers.Kubectl("get", "pipelinerun",
+				"--namespace", deployments.TektonStagingNamespace,
+				stageID,
+				"-o", "jsonpath={.status.conditions[0].status}")
```
Comment (manno) [inline acceptance/api/v1/applications_test.go:128]: I wouldn't line break that much, but ok 🤷

**Review by manno — APPROVED** [review]

File: deployments/registry.go (hunk 2 above)
Comment (andreas-kupries) [reply deployments/registry.go:220]: Should be newly declared for the structure, in the `install_client` code, and as new argument of `apply`.

**Comment by andreas-kupries** [comment]
Only issue I am currently seeing is the bash script for patching the server.
Currently getting an error when copying the exe into the pvc/pod.

```
Copying the binary on the PVC
+ kubectl cp /c/Users/AK/bin/epinio.exe epinio/epinio-copier:/epinio/epinio
error: one of src or dest must be a local file specification
```

(Script was run with `bash -x`)
Exact problem unclear.

File: deployments/registry.go (hunk 1 above)
Comment (manno) [reply deployments/registry.go:168]: I kind of need the changes to `acceptance/helper/epinio/Epinio`, so I'll use this branch as a base then

**Comment by manno** [comment]
> `kubectl cp /c/Users/AK/bin/epinio.exe epinio/epinio-copier:/epinio/epinio error: one of src or dest must be a local file specification`

The `.exe` extension will break everything for me..
Current code is not able  to detect the platform correctly. I'm trying this: https://github.com/epinio/epinio/pull/664/commits/bf81b8f742b88c03777b2573384d445e1c58c352

File: deployments/registry.go (hunk 1 above)
Comment (andreas-kupries) [reply deployments/registry.go]: Done with commit 51460961683b0bc98df5e5bcb40a074708b872c0

**Comment by andreas-kupries** [comment]
Removing the `.exe` from the src file does not help with the `kubectl cp`.

> kubectl cp /c/Users/AK/bin/epinio epinio/epinio-copier:/epinio/epinio
> error: one of src or dest must be a local file specification

Huh. I tried to made sure to have `/c/Users/AK/bin/epinio`, not just `/c/Users/AK/bin/epinio.exe`.
The plain `cp` claims that `epinio` and `epinio.exe` are the same file.
The `ls -l` shows only all `.exe` files, i.e. only `epinio.exe`, no separate `epinio`.

... Trialing using a completely separate file ...

> kubectl cp /c/Users/AK/epinio epinio/epinio-copier:/epinio/epinio
> error: one of src or dest must be a local file specification

No change. And that last file was definitely without an `.exe` extension.

**Review by manno — APPROVED** [review]
