### PR TITLE
Fixed mishandling of scheme prefixes in route specifications

### LINKED ISSUE #2606: App broke after trying update the route with invalid value
**Describe the bug**
When trying to update an app route with a invalid value, eg: https:// in front of the route. (`epinio app update APP_NAME --route https://APP_NAME.domain.com`), after 2 or 4 tries, the app will broke and the app status will turn to `deployment failed`.
To recover the app, you'll need to push it again.

**To Reproduce**

1. Push an app to epinio `epinio app push --name APP_NAME`
2. Try to update the app route with a invalid value - `epinio app update APP_NAME --route https://APP_NAME.domain.com`
3. Run `epinio app list` each time you try to update the route
4. After 2 or 4 times, you'll see the error

**Expected behavior**
- Do not broke the app due a invalid route value.

**Suggestion**
- Make epinioCLI can validate the app route before trying to update the app deployment
- Treat the error to something more familiar to the developer 

**Logs**

image

image

image

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2606

### CODE REVIEW

**Comment by mmartin24** [comment]
Tested on branch and seems to work:

Before:
```
➜  epinio git:(main) epinio app update sampleapp --route https://badname.domain.com                      

🚢  Update application
Namespace: workspace
Application: sampleapp
Routes: 
1: https://badname.domain.com

❌  error updating the app: an error occurred while rolling back the release. original upgrade error: failed to create resource: Ingress.extensions "rsampleapp-httpsbadnam-d861250b733bc7690138f948c3029ad4d789031c" is invalid: [spec.rules[0].host: Invalid value: "https:": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: "https:": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]: no Ingress with the name "rsampleapp-sampleapp19-b1f16f232b2c3898f2e814b7545f669f23dad8aa" found
```

After fix:
- Simple update with `https://...` works:
```
➜  epinio git:(2606-route-schema-prefix-fix) epinio app update sampleapp --route https://badname.domain.com

🚢  Update application
Namespace: workspace
Application: sampleapp
Routes: 
1: https://badname.domain.com
```
- Simple update without `https://` still works:
```
➜  epinio git:(2606-route-schema-prefix-fix) epinio app update sampleapp --route simple-name.domain.com

🚢  Update application
Namespace: workspace
Application: sampleapp
Routes: 
1: simple-name.domain.com

✔️  Successfully updated application
```

- Update with incorrect `https` works also:
```
➜  epinio git:(2606-route-schema-prefix-fix) epinio app update sampleapp --route httpsbad://badname.domain.com

🚢  Update application
Namespace: workspace
Application: sampleapp
Routes: 
1: httpsbad://badname.domain.com

✔️  Successfully updated application
```

- Update with non- allowed (such as capitals) characters still is prevented:
```
➜  epinio git:(2606-route-schema-prefix-fix) epinio app update sampleapp --route httpsbad://BADNAME.domain.com

🚢  Update application
Namespace: workspace
Application: sampleapp
Routes: 
1: httpsbad://BADNAME.domain.com

❌  error updating the app: an error occurred while rolling back the release. original upgrade error: failed to create resource: Ingress.extensions "rsampleapp-domaincom-6f78cc0bd051685a46e7be9a10c54ad289757840" is invalid: [spec.rules[0].host: Invalid value: "BADNAME.domain.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: "BADNAME.domain.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]: no Ingress with the name "rsampleapp-badnamedoma-356aa62d0bbb324d80293cef143b71c095548eb5" found

```

File: internal/api/v1/application/create.go [hunk 1]
```diff
@@ -95,7 +97,14 @@ func Create(c *gin.Context) apierror.APIErrors {
 	var routes []string
 	if createRequest.Configuration.Routes != nil {
 		// Note: Routes can be empty here!
-		routes = createRequest.Configuration.Routes
+		for _, d := range createRequest.Configuration.Routes {
+			// Strip scheme prefixes, if present
+			routeURL, err := url.Parse(d)
+			if err == nil && routeURL.Scheme != "" {
+				d = strings.TrimPrefix(d, routeURL.Scheme+"://")
+			}
```
Comment (enrichman) [inline internal/api/v1/application/create.go:105]: Since we are parsing the URL we should also check for the err (it should not fail but still...):

```suggestion
			routeURL, err := url.Parse(d)
			if err != nil {
				return apierror.NewBadRequestError(err.Error()).WithDetails("failed to parse route")
			}
			if routeURL.Scheme != "" {
				d = strings.TrimPrefix(d, routeURL.Scheme+"://")
			}
```

File: internal/api/v1/application/update.go [hunk 2]
```diff
@@ -288,6 +289,12 @@ func updateRoutes(
 
 	routes := []string{}
 	for _, d := range updateRoutes {
+		// Strip scheme prefixes, if present
+		routeURL, err := url.Parse(d)
+		if err == nil && routeURL.Scheme != "" {
+			d = strings.TrimPrefix(d, routeURL.Scheme+"://")
+		}
```
Comment (enrichman) [inline internal/api/v1/application/update.go:296]: Same, I would add the err check

```suggestion
		routeURL, err := url.Parse(d)
		if err != nil {
			return apierror.NewBadRequestError(err.Error()).WithDetails("failed to parse route")
		}
		if routeURL.Scheme != "" {
			d = strings.TrimPrefix(d, routeURL.Scheme+"://")
		}
```

**Review by enrichman — CHANGES_REQUESTED** [review]
I'm not completely confident about not checking errors.

File: internal/api/v1/application/create.go (hunk 1 above)
Comment (andreas-kupries) [reply internal/api/v1/application/create.go]: ok, commit e5c46e789fa2ccdeb3fd9554f74658ca5bce21e4

File: internal/api/v1/application/update.go (hunk 2 above)
Comment (andreas-kupries) [reply internal/api/v1/application/update.go]: ok, commit e5c46e789fa2ccdeb3fd9554f74658ca5bce21e4

**Review by enrichman — APPROVED** [review]

**Comment by mmartin24** [comment]
Rechecked in `v1.11.0-rc1` and working
