### PR TITLE
Match endpoints for apps and configurations

### LINKED ISSUE #1487: Missing match endpoints for Apps and Configurations
**Describe the bug**

While working on the fix for #1476, see PR #1486 I noticed that a number of older resources are without match endpoints as well. These are

- [x] apps
- [x] configurations

Both use the general list endpoint and then filter the results on the client side.

**Expected behavior**

Have and use proper match endpoints for apps and configurations.

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #1487

### CODE REVIEW

File: acceptance/api/v1/configuration_match_test.go [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+	var namespace string
+
+	When("namespace doesn't exist", func() {
+		It("returns an error", func() {
+			endpoint := fmt.Sprintf("%s%s/namespaces/doesntexist/configurationsmatches",
+				serverURL, v1.Root)
+			response, err := env.Curl("POST", endpoint, strings.NewReader(""))
+			Expect(err).ToNot(HaveOccurred())
+
+			Expect(response.StatusCode).To(Equal(http.StatusMethodNotAllowed))
```
Comment (jimmykarily) [inline acceptance/api/v1/configuration_match_test.go]: Method should be `GET` and status should be `404`. Fixing.

File: acceptance/api/v1/configuration_match_test.go [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+
+			By("create it")
+			env.MakeConfiguration(configurationName)
+		})
+
+		AfterEach(func() {
+			env.DeleteNamespace(namespace)
+		})
+
+		It("lists all apps for empty prefix", func() {
```
Comment (jimmykarily) [inline acceptance/api/v1/configuration_match_test.go:48]:
```suggestion
		It("lists all configurations for empty prefix", func() {
```

File: acceptance/api/v1/configuration_match_test.go [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+			resp := models.ConfigurationMatchResponse{}
+			err = json.Unmarshal(bodyBytes, &resp)
+			Expect(err).ToNot(HaveOccurred())
+
+			// See global BeforeEach for where this namespace is set up.
+			Expect(resp.Names).ShouldNot(BeEmpty())
+			Expect(resp.Names).Should(ContainElements(configurationName))
+		})
+
+		It("lists no apps matching the prefix", func() {
```
Comment (jimmykarily) [inline acceptance/api/v1/configuration_match_test.go:69]:
```suggestion
		It("lists no configurations matching the prefix", func() {
```

File: acceptance/api/v1/configuration_match_test.go [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+
+			resp := models.ConfigurationMatchResponse{}
+			err = json.Unmarshal(bodyBytes, &resp)
+			Expect(err).ToNot(HaveOccurred())
+
+			// See global BeforeEach for where this namespace is set up.
+			Expect(resp.Names).Should(BeEmpty())
+		})
+
+		It("lists all apps matching the prefix", func() {
```
Comment (jimmykarily) [inline acceptance/api/v1/configuration_match_test.go:88]:
```suggestion
		It("lists all configurations matching the prefix", func() {
```

File: internal/api/v1/application/match.go [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+	"github.com/epinio/epinio/internal/api/v1/response"
+	"github.com/epinio/epinio/internal/application"
+	"github.com/epinio/epinio/internal/cli/server/requestctx"
+	apierror "github.com/epinio/epinio/pkg/api/core/v1/errors"
+	"github.com/epinio/epinio/pkg/api/core/v1/models"
+
+	"github.com/gin-gonic/gin"
+)
+
+// Match handles the API endpoint /namespace/:namespace/servicesmatches/:pattern (GET)
```
Comment (jimmykarily) [inline internal/api/v1/application/match.go:16]:
```suggestion
// Match handles the API endpoint /namespace/:namespace/appsmatches/:pattern (GET)
```

File: internal/api/v1/configuration/match.go [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+	"github.com/epinio/epinio/internal/api/v1/response"
+	"github.com/epinio/epinio/internal/cli/server/requestctx"
+	"github.com/epinio/epinio/internal/configurations"
+	apierror "github.com/epinio/epinio/pkg/api/core/v1/errors"
+	"github.com/epinio/epinio/pkg/api/core/v1/models"
+
+	"github.com/gin-gonic/gin"
+)
+
+// Match handles the API endpoint /namespace/:namespace/servicesmatches/:pattern (GET)
```
Comment (jimmykarily) [inline internal/api/v1/configuration/match.go:16]:
```suggestion
// Match handles the API endpoint /namespace/:namespace/configurationsmatches/:pattern (GET)
```

**Review by jimmykarily — APPROVED** [review]
