### PR TITLE
Validate git provider strings, client and server

### LINKED ISSUE #2291: Add validation regarding `provider` field
**Describe the bug**

At the moment we don't have any restriction about the `provider` field used to defin the `git` origin.
To avoid misalignment we have agreed to have a fixed set of values.

For now these will suffice:
```
git
github
github_enterprise
gitlab
gitlab_enterprise
```

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2291

### CODE REVIEW

**Comment by andreas-kupries** [comment]
@richard-cox @torchiaf - Note, the set of strings this code considers as legal can be trivially changed to adapt to the needs of the UI.
See https://github.com/epinio/epinio/pull/2298/files#diff-1ce4bd480f02d0d89d05c5733bbdadacc601e586fe8593e4e70ea34e56a9b469
for the relevant chunk and list.

File: pkg/api/core/v1/models/app.go [hunk 1]
```diff
@@ -30,8 +30,31 @@ const (
 	ApplicationStagingActive = "active"
 	ApplicationStagingDone   = "done"
 	ApplicationStagingFailed = "failed"
+
+	ProviderGit              = "git"
+	ProviderGithub           = "github"
+	ProviderGithubEnterprise = "github_enterprise"
+	ProviderGitlab           = "gitlab"
+	ProviderGitlabEnterprise = "gitlab_enterprise"
```
Comment (enrichman) [inline pkg/api/core/v1/models/app.go:38]: I was thinking that it will be better to have this as a `type` and change the provider to be a `GitProvider` instead of a generic string. This will help us on being stricter during the creation/handling of this value, and be sure to use one of the right one.

Something like:

```golang
type GitProvider string

const (
	ProviderUnknown = GitProvider("unknown")
	ProviderGit     = GitProvider("git")
	ProviderGithub  = GitProvider("github")
)

func GitProviderFromString(provider string) (GitProvider, error) {
	switch provider {
	case "git":
		return ProviderGit, nil
	case "github":
		return ProviderGit, nil
	default:
		return ProviderUnknown, errors.New("unknown provider")
	}
}

```

I really miss enums sometimes.

**Review by enrichman — CHANGES_REQUESTED** [review]

File: pkg/api/core/v1/models/app.go (hunk 1 above)
Comment (andreas-kupries) [reply pkg/api/core/v1/models/app.go:38]: Certainly doable. The conversion function acts as the validator.

File: internal/manifest/manifest.go [hunk 2]
```diff
@@ -154,6 +159,16 @@ func UpdateSources(manifest models.ApplicationManifest, cmd *cobra.Command) (mod
 		kind = models.OriginGit
 		origins++
 
+		// Standard provider, and conditional override by the user
+		gitRef.Provider = models.ProviderGit
```
Comment (enrichman) [inline internal/manifest/manifest.go:163]: I was thinking that maybe we could also check for the standard urls for Github and Gitlab:

```go
func GitProviderFromOriginURL(url string) {
	u, err := url.Parse("https://github.com/ndcsjk/sdhbnis")
	// check for u.Host == github.com or gitlab.com
}
```
and then 
```go
provider, err := models.GitProviderFromOriginURL(gitURL)
if err != nil {
	// log something about the error
	gitRef.Provider = models.ProviderGit
} else {
	gitRef.Provider = provider
}
```

What do you think? The `--git-provider` could be provided anyway to overwrite this behaviour.

Comment (andreas-kupries) [reply internal/manifest/manifest.go:163]: I feel the beginning of feature creep here. Willing to try this one thing. And CI just went :heavy_check_mark: :(

Comment (andreas-kupries) [reply internal/manifest/manifest.go]: See commit 14309cf6159097d6d95aff0be97dfe35a0bdc498

**Review by enrichman — APPROVED** [review]

**Comment by mmartin24** [comment]
Checked new  `--git-provider` flag with `gitlab` and working:

```
epinio push --name testatpp-gitlab-cli-1 --git-provider gitlab --git https://gitlab.com/richard-cox/epinio-sample-app,bb6883114668e9aed4964ed3f60bed3bc623c202
```

Output:
```
─────────────────────────────────────────────────────────── Logs(workspace/rtestatpp-gitlab-cli-1-7ad57b18960c71700e822a7f79d2a3597aeswj67:rtestatpp-gitlab-cli-1-7ad57b18960c71700e822a7f79d2a3597aed6f06)[1m] ───────────────────────────────────────────────────────────┐
│                                                                                                     Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                                                                                                      
│ chatty app .... is chatty                                                                                                                                                                                                                                                 
│ chatty app .... is chatty     
```
