### PR TITLE
Remove dependency on `Deployment` resource as entry for app workload

### LINKED ISSUE #1629: Pushing with an application template without a deployment stalls
**Describe the bug**

If I edit the deployment manifest to use a Statefulset instead of a Deployment, the push command doesn't exit after the build and deploy. I can tell from kubectl that the application is running correctly (and can access the app) so the only issue is that the CLI doesn't know that the app is alive.

**To Reproduce**
Add a new application template with my statefulset template: https://chameleons.sfo3.digitaloceanspaces.com/epinio-stateful-application-0.1.15.tgz 

Push an application with this template.

**Expected behavior**
I would expect the CLI to return successfully when the application is running

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fix #1629.

  - With our use of helm charts and --wait'ing for their deployment it is not really necessary any longer.
  - It is specific to kube Deployments.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Chart PR https://github.com/epinio/helm-charts/pull/253 to support the removal of the dependency on Deployments.

File: internal/api/v1/application/exec.go [hunk 1]
```diff
@@ -71,12 +71,12 @@ func (hc Controller) Exec(c *gin.Context) apierror.APIErrors {
 		podToConnect = podNames[0]
 	}
 
-	deployment, err := workload.Deployment(ctx)
+	appData, err := workload.Get(ctx, 0)
```
Comment (jimmykarily) [inline internal/api/v1/application/exec.go:74]: As we discussed in a call, `Workload` struct seems to be superfluous and can be removed (merged with the `AppDeployment`). Then we can implement a `GetWorkload` method on the app itself instead of this `Get`. We won't need to pass the desired instances then.

Comment (andreas-kupries) [reply internal/api/v1/application/exec.go:74]: Larger discussion got triggered ... Defering full resolution into new ticket https://github.com/epinio/epinio/issues/1657

For now a better intermediate change would be to move the `desiredInstances` argument from `Get` to `NewWorkload`.

File: internal/cli/usercmd/push.go [hunk 2]
```diff
@@ -237,10 +237,10 @@ func (c *EpinioClient) Push(ctx context.Context, params PushParams) error { // n
...
 	c.ui.ProgressNote().KeeplineUnder(1).Msg("Creating application resources")
 
-	_, err = c.API.AppRunning(appRef)
-	if err != nil {
-		return errors.Wrap(err, "waiting for app failed")
-	}
+	// _, err = c.API.AppRunning(appRef)
+	// if err != nil {
+	// 	return errors.Wrap(err, "waiting for app failed")
+	// }
```
Comment (jimmykarily) [inline internal/cli/usercmd/push.go:243]:
```suggestion
```

File: internal/cli/usercmd/push.go [hunk 3]
```diff
@@ -237,10 +237,10 @@ func (c *EpinioClient) Push(ctx context.Context, params PushParams) error { // n
...
```
Comment (jimmykarily) [inline internal/cli/usercmd/push.go:244]:
```suggestion
```

Comment (jimmykarily) [reply internal/cli/usercmd/push.go:244]: github doesn't let me select the additional empty line that needs to be deleted too :(

**Comment by jimmykarily** [comment]
Would have been nice to have an application chart with `Statefulset` to test this (@agracey [promised one](https://github.com/epinio/epinio/issues/1629#issuecomment-1194032218)). Let's implement the test on another PR.

File: internal/api/v1/application/exec.go (hunk 1 above)
Comment (andreas-kupries) [reply internal/api/v1/application/exec.go]: Intermediate change done in commit 6b070caadb31c350cc874eb9fb7cb307562b0bbd

File: internal/api/v1/application/running.go [hunk 4]
```diff
@@ -1,20 +1,34 @@
...
+//
+// __API PORTABILITY NOTE__
+//
+// With the switch to deployment of apps via helm, and waiting for the helm deployment to
+// be ready before returning this endpoint is technically superfluous, and it should never
+// fail. The command line has been modified to not invoke it anymore.
+//
+// It is kept for older clients still calling on it. Because of that it is also kept
+// functional. Instead of checking for an app `Deployment` and its status it now checks
+// the app `Pod` stati.
```
[the remark this answers is not in the document]
Comment (andreas-kupries) [reply internal/api/v1/application/running.go:31]: We can have more than one pod, thus the plural.

File: internal/application/workload.go [hunk 5]
```diff
@@ -185,24 +156,53 @@ func (a *Workload) Replicas(ctx context.Context) (map[string]*models.PodInfo, er
...
+	var createdAt time.Time
+	var stageID string
+	var username string
+	var controllerName string
+
+	if len(podList) > 0 {
+		// Pods found. replace defaults with actual information.
+
+		// Initialize various pieces from the first pod ...
+		createdAt = podList[0].ObjectMeta.CreationTimestamp.Time
```
Comment (jimmykarily) [inline internal/application/workload.go:184]: This won't reflect reality anymore. A Deployment may be scaled up or down, causing Pods to appear and disappear. The age of any Pod may have nothing to do with the age of the "workload". That said, the age of the workload is probably nonsense. How old is the "workload" of an application that run 1 Pod for 3 hours, then was scaled down to 0 for an hour or two and then scaled back up to 3 Pods for 10 hours? If we imply that the age of the workload is the time since any Pod was created, then in most cases what we need is the time of creation of the application itself, unless the application was originally created without a workload and stayed like that for while. In that case though, I don't think the creation date of the first Pod is useful in any way.

Unless I'm missing something and this breaks the cli or the UI in a very bad way, I suggest we remove this field from the workload. This information should be provided for the individual Pods.

File: internal/application/workload.go [hunk 6]
```diff
@@ -185,24 +156,53 @@ func (a *Workload) Replicas(ctx context.Context) (map[string]*models.PodInfo, er
...
+		stageID = podList[0].ObjectMeta.Labels["epinio.io/stage-id"]
```
Comment (jimmykarily) [inline internal/application/workload.go:185]: This can also be non-true. When pushing an application again, the old Pods co-exist with the new ones for some time (usually for very little). After a while things balance out but I'm not sure this won't lead to wrong assumptions in some cases (e.g. getting the old stage id assuming it's the new one). To suggest a better alternative, we would have to find all consumers. Maybe we can get this information from the application itself (as part of this? https://github.com/epinio/epinio/issues/1657)

File: internal/application/workload.go (hunk 5 above)
Comment (andreas-kupries) [reply internal/application/workload.go:184]: I believe you missed the code later in the loop which merges the dates from all the pods, and takes the youngest.
Lines 190-193.

Regarding usage ... The cli uses it for the general `Age` information, see (***) below

```
|         KEY          |                    VALUE                     |
|----------------------|----------------------------------------------|
| Origin               | /home/work/SUSE/dev/epinio/assets/sample-app |
| Created              | 2022-07-26 15:01:14 +0200 CEST               |
| Status               | 1/1                                          |
| Username             | admin                                        |
| Running StageId      | e6b05fbad294fc4b                             |
| Last StageId         | e6b05fbad294fc4b                             |
| Age                  | 6m0s                                         | ***
| Active Routes        |                                              |
|                      | fox-a279f.172.19.0.4.omg.howdoi.website      |
| App Chart            | standard                                     |
| Desired Instances    |                                            1 |
| Bound Configurations |                                              |
| Environment          |                                              |
```

The cli also show per-pod age.
No idea about usage in the UI . @richard-cox ping

Note that a full removal of the field from the structure is an API change now.

For best compatibility we should keep the field, even if we decide to not fill it anymore, i.e. leave it at Go's zero value.

File: internal/application/workload.go (hunk 6 above)
Comment (andreas-kupries) [reply internal/application/workload.go:185]: I see, like `desiredReplicas`.

Comment (jimmykarily) [reply internal/application/workload.go:185]: yes

File: internal/application/workload.go (hunk 5 above)
Comment (jimmykarily) [reply internal/application/workload.go:184]: Yes I missed that part but my comment still stands, no Pod age is guaranteed to match a "Deployment age" whatever the latter means.

Comment (richard-cox) [reply internal/application/workload.go:184]: I might have got confused with the terminology here, but the UI presents app, deployment and 'instances' info as below

image

- App age at the top (from `meta.createdAt`)
- No deployment age (though there would be value in showing, from `deployment.createdAt`)
- 'Instances' Age per row. (from `deployment.replicas` and their `createdAt` property)

I would be nice to keep all of the above, unless the replicaSet age won't differ between entries

Comment (andreas-kupries) [reply internal/application/workload.go:184]: @richard-cox 
The `deployment age` was from the `Deployment` resource of the app. With us not knowing anymore if the top controller is a `Deployment`/`StatefulSet`/other I am currently trying to synthesize something sensible from the App Pods (I take the ... oldest Pod as the reference) ... @jimmykarily only saw me taking the first Pod.

**Comment by agracey** [comment]
Here's an example chart that should work: 
https://github.com/epinio/helm-charts/tree/additional_application_charts/chart/stateful-appliction 

It's packaged up at: 
https://chameleons.sfo3.digitaloceanspaces.com/epinio-stateful-application-0.1.15.tgz

Let me know if there's any issue with it. I haven't tried it recently so will test shortly once I spin up an environment

**Comment by andreas-kupries** [comment]
Local manual check of the failed ops is ok. Local CI focused on the failing test was ok also. Retrying main CI now.

File: internal/application/workload.go (hunk 5 above)
Comment (andreas-kupries) [reply internal/application/workload.go:184]: > match a "Deployment age" whatever the latter means.

The "Deployment age" was literally the `Deployment`'s `MetaData.CreatedAt`.

Does the go kube client stuff have a general way of getting a resource's meta data without knowing the kind of the resource ? I.e. just from the name+namespace ?

If yes, then we can get rid of the code synthesizing something from the pods in favor of pulling from the controller resource again. Note, at that point the new `epinio.io/app-container` label is also important as naming the controller resource.
We could of course separate this and have a `epinio.io/controller` label as well.

Comment (andreas-kupries) [reply internal/application/workload.go:184]: ... Oh, it might be do-able via `unstructured`

Comment (jimmykarily) [reply internal/application/workload.go:184]: There is a way to discover what controller the Pod belongs too but I'm not sure if it's guaranteed (e.g. what happens if the application chart simply creates Pods without Deployments or Statefulsets?).

The Pod has an owner field. In the case of Deployments that is a ReplicaSet. The ReplicaSet has an owner, which is the Deployment. I assume there is a similar chain of owners for a Statefulset. We may not even have to go that up, maybe the createdAt field of the first Owner in the chain is enough.

If there is no owner (e.g. a custom application chart creates just Pods for whatever reason), we could opt for the current solution.

I wonder if it's too complicated logic, to get information that makes little sense imho.

Comment (andreas-kupries) [reply internal/application/workload.go:184]: Or not ... Seems even the dynamic client wants me to tell it the kind of resource ahead of time ... I guess that is because a resource is identified uniquely only by all three of (name, namespace, and kind).

In that case case the chart would have to tell Epinio the kind, another label on the pods.

**Review by jimmykarily — APPROVED** [review]

File: internal/application/workload.go (hunk 5 above)
Comment (andreas-kupries) [reply internal/application/workload.go:184]: Ok. Stopping here. Putting this all on #1657 ...

**Comment by andreas-kupries** [comment]
> Here's an example chart that should work: https://github.com/epinio/helm-charts/tree/additional_application_charts/chart/stateful-appliction
> 
> It's packaged up at: https://chameleons.sfo3.digitaloceanspaces.com/epinio-stateful-application-0.1.15.tgz
> 
> Let me know if there's any issue with it. I haven't tried it recently so will test shortly once I spin up an environment

New ticket #1658 to handle this.
