### PR TITLE
detect users defined multiple times and reject them

### LINKED ISSUE #2692: Same username should not be possible to be assigned
# Issue
It is possible to create 2 or more users with the same username. Login (and possibly all the other APIs) are not deterministic.

# To reproduce

- Create two users with different metadata name but same `username`

```yaml
cat <<EOF | kubectl apply -f -                                                              
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "admin"
  name: my-epinio-user-admin
  namespace: epinio
stringData:
  username: myuser
  namespaces: workspace
  password: "\$2a\$10\$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
EOF
```

```yaml
cat <<EOF | kubectl apply -f -                                                              
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "admin"
  name: my-epinio-user
  namespace: epinio
stringData:
  username: myuser
  namespaces: workspace
  password: "\$2a\$10\$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
EOF
```
- Go to secrets and decode `my-epinio-user-admin` and `my-epinio-user`

Image

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #2692 

users defined multiple times are filtered, i.e. seen as not existing, primarily.
enough data is kept to report them as `defined multiple times`, instead of as `not `found`.

### CODE REVIEW

**Review by enrichman — CHANGES_REQUESTED** [review]
Having a look at this I've seen a couple of things that were probably leftovers.
I would make this changes:

1) Drop the `loadUsersMap` and use the  `authService.GetUserByUsername`

The `loadUsersMap` func doesn't make really sense. IIRC it was used/needed for a Gin automatic detection for the BasicAuth, but we are doing a different check now, so it can be probably removed completely, using directly the `authService.GetUserByUsername`, since we need a specific user.

This will be very convenient, because we can immediately check if the error returned is the `ErrUserMultiple`.

2)  Make the `authService.GetUsers` private -> `authService.getUsers`

The `GetUsers` func at the moment can be used only privately. The only other place where it's used is in the `internal/api/v1/middleware/token.go`, but we need to get the specific user also there (and so eventually trigger the same `ErrUserMultiple` error if needed).

3) `authservice.GetUsers` could return the same ErrUserMultiple error

Probably we should trigger the same error also in the `GetUsers`, but maybe this means that we are interested to know who are the users with this "wrong" configuration.
To do this we can create a more "complex" error type:

```go
type ErrUserMultiple struct {
	UsersCount map[string]int
}

func (e *ErrUserMultiple) Error() string {
	return fmt.Sprintf("found %d users with the same username", len(e.UsersCount))
}
```

This will change the check to something like this:

```go
var errMultiple *ErrUserMultiple
errors.As(err, &errMultiple) {
	// do something
}
```

This could be useful when in the future we would like to know from the `GetUsers` which are the wrong users.

4) Drop the `DefinitionCount`

This field is never cleared, so the `AuthService` will keep the state. It's not also a field that seems to be part of the "object", but scoped to the request. Not sure if we are keeping the `AuthService` instance, but if so that means that we would need to restart Epinio, if that's the case. I would remove it anyway. It's not needed.

5) Rename the error

Change `ErrUserMultiple` to `ErrMultipleUsersFound` or `ErrUsernameConflict`.
If moving to the error struct the convention is to have the `XXXError`.

So:

```go
var ErrMultipleUsersFound = errors.New("dbsjksdjk")
// or
type ErrUserMultiple struct{}
```

6) Does it work?

I have not tested it but the `GetUserByUsername` seems to return early:

```go
for _, user := range users {
	if user.Username == username {
		return user, nil
	}
}

count, ok := s.Counts[username]
if ok && (count > 1) {
	s.Logger.V(1).Info("user defined multiple times", "user", username, "count", count)

	return User{}, ErrUserMultiple
}
```

7) Tests

If possible I would add a test (unit or acceptance). The unit should be pretty easy and fast to add. We already have them setup, and we just need to return the secrets from the FakeSecretInterface.

The acceptance are a bit more annoying.

**Comment by andreas-kupries** [comment]
> I have not tested it but the GetUserByUsername seems to return early:

A pity that you did not attach this comment to the specific code.
Remember: A user defined multiple times is filtered out when the users are loaded. It is effectively 'not found'.
The loop does not find it, and the code reaches the check where it determines of the user truly does not exist, or just because of a multi-definition.

**Comment by andreas-kupries** [comment]
I will now make changes, with commits as separate as possible, and quoting relevant parts of the comment in the commit message. It is too difficult to disentangle them otherwise.

**Comment by enrichman** [comment]
Thank you. Yes, sorry about not commenting the code but unfortunately Github doesn't let you comment the code that was not changed, and most of the comments were not related to the actual changes. :slightly_frowning_face: 

I'll try to comment better in the second round. :+1:

**Comment by andreas-kupries** [comment]
> most of the comments were not related to the actual changes

I am ok with such comments attached to actual changes and refering to the unchanged parts.

**Comment by andreas-kupries** [comment]
> The only other place where it's used is in the internal/api/v1/middleware/token.go

no. Unit testing uses it as well, and cannot test a private function.

```
% golangci-lint run --skip-files docs.go --timeout 5m
internal/auth/action_test.go:1: : # github.com/epinio/epinio/internal/auth_test [github.com/epinio/epinio/internal/auth.test]
internal/auth/auth_test.go:79:39: authService.getUsers undefined (type *"github.com/epinio/epinio/internal/auth".AuthService has no field or method getUsers)
```

**Comment by andreas-kupries** [comment]
Changes addressing comments pushed.

File: internal/auth/auth.go [hunk 1]
```diff
@@ -33,12 +33,15 @@ import (
 )
 
 var (
-	ErrUserNotFound = errors.New("user not found")
+	ErrUserNotFound     = errors.New("user not found")
+	ErrUsernameConflict = errors.New("this user is defined multiple times, please talk to the operator")
```
Comment (enrichman) [inline internal/auth/auth.go:37]: I would just tell what happened and not what to do:

```suggestion
	ErrUsernameConflict = errors.New("username defined multiple times")
```

File: internal/auth/auth.go [hunk 2]
```diff
@@ -62,19 +65,42 @@ func NewAuthService(logger logr.Logger, cluster *kubernetes.Cluster) *AuthServic
...
+	userCount := DefinitionCount{}
+
+	for _, secret := range secrets {
+		name := string(secret.Data["username"])
+		count, ok := userCount[name]
+		if !ok {
+			userCount[name] = 1
+			continue
+		}
+		userCount[name] = count + 1
```
Comment (enrichman) [inline internal/auth/auth.go:92]: The zero value of a int is already 0, so this can be changed to:

```suggestion
		count := userCount[name]
		userCount[name] = count + 1
```

File: internal/auth/auth.go [hunk 3]
```diff
@@ -62,19 +65,42 @@ func NewAuthService(logger logr.Logger, cluster *kubernetes.Cluster) *AuthServic
...
+		return nil, nil, errors.Wrap(err, "error getting users secrets")
 	}
 
 	users := []User{}
 	usernames := []string{}
 
+	// map of per-user definition counts, to detect users with conflicting definitions
+	userCount := DefinitionCount{}
+
+	for _, secret := range secrets {
```
Comment (enrichman) [inline internal/auth/auth.go:85]: I'm commenting here but it's about the two loops. It's probably easier to read if we fetch all the users, mapping the duplicates, and then filter them.

Please be aware that the `newUserFromSecret` is suppose to hide all the "secret-user" internal, to avoid knowing from other parts which data contains what (ie: `secret.Data["username"]`). This is helpful if we change something in the secrets, and to avoid typos.

```go
allUsers :=  []User{}
usernames := []string{}
userCount := DefinitionCount{}

// fetch and convert all the users, mapping the duplicates
for _, secret := range secrets {
	user := newUserFromSecret(s.Logger, secret)
	allUsers = append(allUsers, user)
	usernames = append(usernames, user.Username)

	count := userCount[user.Username]
	userCount[user.Username] = count + 1
}

filteredUsers :=  []User{}

// filter duplicates
for _, user := range allUsers {
	if userCount[user.Username] > 1 {
		s.Logger.V(1).Info("skip duplicate user", "user", user.Username)
		continue
	}
	filteredUsers = append(filteredUsers, user)
}
```

File: internal/auth/auth.go [hunk 4]
```diff
@@ -33,12 +33,15 @@ import (
...
 var (
-	ErrUserNotFound = errors.New("user not found")
+	ErrUserNotFound     = errors.New("user not found")
+	ErrUsernameConflict = errors.New("this user is defined multiple times, please talk to the operator")
 )
 
 //counterfeiter:generate -header ../../LICENSE_HEADER k8s.io/client-go/kubernetes/typed/core/v1.SecretInterface
 //counterfeiter:generate -header ../../LICENSE_HEADER k8s.io/client-go/kubernetes/typed/core/v1.ConfigMapInterface
 
+type DefinitionCount map[string]int
```
Comment (enrichman) [inline internal/auth/auth.go:43]: Not sure about the name, but I've nothing better to propose.

**Review by enrichman — CHANGES_REQUESTED** [review]
Some small comments. Thank you!

File: internal/auth/auth.go (hunk 1 above)
Comment (andreas-kupries) [reply internal/auth/auth.go:37]: ok

File: internal/auth/auth.go (hunk 2 above)
Comment (andreas-kupries) [reply internal/auth/auth.go:92]: Actually, then we do not need a helper variable either. ok

File: internal/auth/auth.go (hunk 3 above)
Comment (andreas-kupries) [reply internal/auth/auth.go:85]: I had hoped to avoid the construction of `User` structures for the conflicting parts. That said, with the encapsulation argument, it is better to do so. Ok

File: internal/auth/auth.go (hunk 2 above)
Comment (andreas-kupries) [reply internal/auth/auth.go]: done. commit b04ac0d8192ab565f309eb40f53dc5acf34710cb

File: internal/auth/auth.go (hunk 3 above)
Comment (andreas-kupries) [reply internal/auth/auth.go:83]: done. commit b04ac0d8192ab565f309eb40f53dc5acf34710cb

**Review by enrichman — APPROVED** [review]
LGTM
