### PR TITLE
Cluster patching for Windows. Plus documentation.

### LINKED ISSUE #660: Windows binary should default to "--no-colors"
As Windows cannot [display emojies](503) or handle [color output](659) in a reasonable way, the `--no-colors` flag should default to `true` in Windows.

### LINKED ISSUE #672: Windows install fails on dex deployment
* epinio (built from source) @ c7afb19

* Windows 10 Home, Kubernetes via Rancher Desktop

* Running `epinio install` in PowerShell

Installation fails with
```
panic: Deployment dex failed with error: Failed to extract embedded file:  - file does not exist


goroutine 52 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc000254150, 0x24ca9b0, 0xc000034050, 0x24d5670, 0xc00044b400, 0x24d9df8, 0xc00020d0b0, 0xc00020d094)
        /abuild/projects/rancher/epinio/epinio/internal/cli/clients/install_client.go:168 +0x23f
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
        /abuild/projects/rancher/epinio/epinio/internal/cli/clients/install_client.go:165 +0x10e5
```

### LINKED ISSUE #673: '--no-colors' option has no effect on Windows
Passing the `--no-colors` command line option to Epinio on Windows has no visual effect.

### PR DESCRIPTION
**Pull request by andreas-kupries**
References #503 
Fixes #673 
Fixes #672
Fixes #660

### Notes

- `kubectl cp` syntax specifies a pod file as `pod`:`path`. Note the `:`. That is a special character on Windows and breaks the command. This got replaced by a series of `kubectl exec` commands using a tar command client- and pod-side to copy the file in, move it into the proper place, and ensure correct permissions.
- Note that in the above we cannot use absolute paths, like `/epinio` either, they are breaking the command as well. Because on Windows these are __drive-relative__ paths and get expanded by the kubectl binary before trying to use them. Luckily for us relative paths, i.e `epinio` do work. Because the CWD for `kubectl exec` is the root directory of the pod, making relative and absolute paths equivalent.
- Newly added to the patch script is the `EPINIO_BINARY_TAG` variable. It contains the tag for the image the binary will be placed in. From within a git checkout the default, provided by a `git describe ...` command is good enough. Outside of a checkout use `make tag` in the checkout to determine the tag, and then set the environment variable explicitly.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Confirmed working :tada: :fireworks: :green_heart:

**Review by manno — APPROVED** [review]

File: scripts/patch-epinio-deployment.sh [hunk 1]
```diff
@@ -60,7 +66,19 @@ echo "Waiting for dummy pod to be ready"
 kubectl wait --for=condition=ready pod -n epinio epinio-copier
 
 echo "Copying the binary on the PVC"
-kubectl cp ${EPINIO_BINARY_PATH} epinio/epinio-copier:/epinio/epinio
+# Notes
+# 1. kubectl cp breaks because of the colon in `pod:path`. Thus the more complex tar construction.
```
Comment (jimmykarily) [inline scripts/patch-epinio-deployment.sh:70]: Will probably be fixed at some point: https://github.com/kubernetes/kubernetes/pull/102047
