### PR TITLE
fix: unwanted retry of `namespace create` for existing namespace

### LINKED ISSUE #1081: Do not retry in Cli if the namespace already exists
Do not retry to create the namespace in Cli if it already exists. Follow up for the mentioned TODO:

https://github.com/epinio/epinio/blob/1cc932fb809132ad00212715aa98f882e3f1ac0d/internal/api/v1/namespace/create.go#L40-L43

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #1081 

- retry removed completely
- became superfluous again, with initial namespace creation moved to external installer

### CODE REVIEW

File: pkg/api/core/v1/client/namespaces.go [hunk 1]
```diff
@@ -22,33 +16,7 @@ func (c *Client) NamespaceCreate(req models.NamespaceCreateRequest) (models.Resp
 		return resp, nil
```
Comment (enrichman) [inline pkg/api/core/v1/client/namespaces.go:16]: It's not related to the PR but should be this returning `err` instead of `nil`?

Comment (andreas-kupries) [reply pkg/api/core/v1/client/namespaces.go:16]: Quite possible. I will make that change and see if that breaks CI.

Comment (andreas-kupries) [reply pkg/api/core/v1/client/namespaces.go]: Lets see what CI says about ea54e449a52827369fb0c5fa3158ea06622bd4d8

**Review by enrichman — APPROVED** [review]
