### PR TITLE
Don't list orgs when targeting a specific one

### LINKED ISSUE #958: Namespace#Index shouldn't fail when a namespace is deleted mid-flight
The "Index" endpoint, after finding all the namespaces, tries to populate them with more data (applications, services, etc). If a namespace is removed during that time, the action fails. It should instead remove that namespace from the internal list and continue with the rest.

This bug is causing acceptance tests to fail randomly because some tests are listing namespaces while other ginkgo nodes are deleting their namespaces.

### PR DESCRIPTION
**Pull request by jimmykarily**
because tests fail when an org is deleted while "list" endpoint is still
running.

Fixes #958

### CODE REVIEW

**Review by andreas-kupries — DISMISSED** [review]

File: internal/api/v1/namespace/index.go [hunk 1]
```diff
@@ -34,12 +35,16 @@ func (oc Controller) Index(c *gin.Context) apierror.APIErrors {
 	for _, org := range orgList {
 		appNames, err := namespaceApps(ctx, cluster, org.Name)
 		if err != nil {
-			return err
+			return apierror.InternalError(err)
```
Comment (andreas-kupries) [inline internal/api/v1/namespace/index.go:38]: Shouldn't this also check for a missing namespace ?
I mean, you check for missing namespace after getting the services.
IMHO this check should also be done after getting the apps, above.

**Review by andreas-kupries — CHANGES_REQUESTED** [review]
Looks to be a partial fix.

File: internal/api/v1/namespace/index.go (hunk 1 above)
Comment (jimmykarily) [reply internal/api/v1/namespace/index.go:38]: namespaceApps won't generate an error if a namespace is missing. That's because it never runs `organization.Exists` like the `namespaceServices` does (through `services.List`). It's inconsistent but as far as the fix is concerned, it can't break anymore.

Comment (andreas-kupries) [reply internal/api/v1/namespace/index.go:38]: Oh, I see now. It uses the `ListAppRefs` and simply gets an empty slice ... Ok then.

**Review by andreas-kupries — APPROVED** [review]

File: internal/api/v1/namespace/index.go (hunk 1 above)
Comment (jimmykarily) [reply internal/api/v1/namespace/index.go:38]: We could achieve consistency by making the `services.List` a bit more resilient, if it didn't check for the existence of the namespace. It could simply set it in the selector and return an empty list if the namespace is gone. But since this is a hot fix, let's not change more than we have to.
