### PR TITLE
Fixed a mishandling of apps in `delete --unbind`

### LINKED ISSUE #2551: Deleting a service with a bound app will prevent the app being bound to any service
**Describe the bug**
After a service is bound to an application, deleting the service with
```
DELETE /api/v1/namespaces/<ns>/services?services[]=<service name> {"unbind": true}
```
results in the app unable to be bound to a new service with 
```
POST /api/v1/namespaces/<ns>/services/<new service name>/bind POST {"app_name":"<app name>"}
```
```
{"errors":[{"status":500,"title":"configuration not found","details":"\nServer Backtrace: configuration not found"}]}
```

**To Reproduce**
1. Run the latest nightly UI
2. Create any type of application
3. Create a service and bind the application to it
    - Note the API requests made to create the service, fetch the service and the bind to it 
5. From the service list delete the service
    - Note the API request to delete the service
6. Create a new service and bind the application to it
   - Note the API  to bid will fail with `configuration not found`

**Expected behavior**
Request to bind completes

**Cluster (please complete the following information):**
 - Provider: k3d
 - Kubernetes Version: v1.25.7+k3s1

**Desktop/CLI (please complete the following information):**
 - Epinio Version: v1.9.0-23-g58d35b2e

**Additional context**
- Originating from https://github.com/epinio/ui/issues/289#issuecomment-1706537496
- I noticed on one run that trying to concurrently delete services where at least on service had a failed bind attempt also resulted in the same `configuration not found` error. 
- Possibly irrelevant, the UI now no longer waits for the service instance to be `deployed` before binding. This works (see step 3 above) but might leave something in a bad state?
- Using

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fix #2551

### CODE REVIEW

File: internal/api/v1/service/delete.go [hunk 1]
```diff
@@ -101,7 +102,7 @@ func Delete(c *gin.Context) apierror.APIErrors {
 			return apierror.InternalError(err)
 		}
 
-		logger.Info(fmt.Sprintf("configurationSecrets found %+v\n", serviceConfigurations))
+		logger.Info("configurations", "service", service.Meta.Name, "configurations", serviceConfigurations)
```
Comment (enrichman) [inline internal/api/v1/service/delete.go:105]: Since the `serviceConfigurations` are `v1.Secrets` the logging will be too verbose/annoying.
I would print only the len of them, and then in the loop we could print what we need (name and namespace?).

```go
logger.Info(fmt.Sprintf("found %d configurations", len(serviceConfigurations)), "service", service.Meta.Name)

for _, secret := range serviceConfigurations {
	logger.Info(fmt.Sprintf("configuration secret for service '%s'", service.Meta.Name),
		"name", secret.Name,
		"namespace", secret.Namespace,
	)
}
```

File: internal/api/v1/service/delete.go [hunk 2]
```diff
@@ -125,6 +126,8 @@ func Delete(c *gin.Context) apierror.APIErrors {
 
 	boundAppNames = helpers.UniqueStrings(boundAppNames)
 
+	logger.Info("bound to", "apps", boundAppNames, "count", len(boundAppNames), "unbind?", deleteRequest.Unbind)
```
Comment (enrichman) [inline internal/api/v1/service/delete.go:129]: The k/v pairs are meant to be used in structured logs. Having a key with `?` is possibly an issue with parser, greps or whatever, also in json.

```suggestion
	logger.Info("bound to", "apps", boundAppNames, "count", len(boundAppNames), "unbind", deleteRequest.Unbind)
```

File: internal/api/v1/service/delete.go [hunk 3]
```diff
@@ -146,6 +153,8 @@ func Delete(c *gin.Context) apierror.APIErrors {
 
 			// ... And run the unbind per app and service.
 			for serviceName, serviceConfigurations := range infoMap {
+				logger.Info("unbinding of", "service", appName, serviceName)
```
Comment (enrichman) [inline internal/api/v1/service/delete.go:156]: Same because of the structured logs:

```suggestion
				logger.Info("unbinding of service", "app", appName, "service", serviceName)
```

File: internal/api/v1/service/unbind.go [hunk 4]
```diff
@@ -81,7 +80,7 @@ func Unbind(c *gin.Context) apierror.APIErrors {
 		return apierror.InternalError(err)
 	}
 
-	logger.Info(fmt.Sprintf("configurationSecrets found %+v\n", serviceConfigurations))
+	logger.Info("configurationSecrets", "secrets", serviceConfigurations)
```
Comment (enrichman) [inline internal/api/v1/service/unbind.go:83]: Same as before.

**Review by enrichman — COMMENTED** [review]
Some small comments

File: internal/api/v1/service/unbind.go (hunk 4 above)
Comment (andreas-kupries) [reply internal/api/v1/service/unbind.go]: done with commit f59a6fe6a7e2948f7004856dd35ce18afc625817

File: internal/api/v1/service/delete.go (hunk 3 above)
Comment (andreas-kupries) [reply internal/api/v1/service/delete.go]: done with commit f59a6fe6a7e2948f7004856dd35ce18afc625817

File: internal/api/v1/service/delete.go (hunk 2 above)
Comment (andreas-kupries) [reply internal/api/v1/service/delete.go]: done with commit f59a6fe6a7e2948f7004856dd35ce18afc625817

**Review by enrichman — APPROVED** [review]
