### PR TITLE
Fix: mishandling of commit ids in git upload

### LINKED ISSUE #1642: Failure to push an application from git repository where revision is a commit id
**Describe the bug**

Of the two command

1. `epinio push --name fox --git=https://github.com/richard-cox/epinio-sample-app,a9665a17e4d863cc7b6d6a40ea4d4d51d0bcd12c`
2. `epinio push --name fox --git=https://github.com/richard-cox/epinio-sample-app,master`

the first fails with an internal server error. The commit id/hash is treated as a branch name, and such does exist.

**To Reproduce**

See above.

**Expected behavior**

No error, working push

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fixes #1642 

The code mishandled commit ids in the git upload code. It exclusively treated the revision as branch name, and a commit id usually (*) is not.

(*) Git is actually perfectly fine to use a commit id looking string as a branch name. On the other side, this make it impossible to syntactically distinguish commit id from branch.

This is why the code tries the `revision` as branch first, and then that fails tries it as commit id (if it looks like such).

### CODE REVIEW

**Comment by enrichman** [comment]
Could we use something like the `git rev-parse` to handle only one case?

Basically it should be possible to resolve "everything" to an hash with the `rev-parse` command, and so we can fetch the commit directly.

```
-> % git rev-parse origin/1642-git-upload-accept-commit-id
a662cd927e9af78fdf5a5b7fd880268744bbacc

-> % git rev-parse a662cd927e9af78fdf5a5b7fd880268744bbacc3
a662cd927e9af78fdf5a5b7fd880268744bbacc3
```

This seems supported: https://github.com/go-git/go-git/blob/bf3471db54b0255ab5b159005069f37528a151b7/_examples/revision/main.go
while I have not tried.

```go
h, err := r.ResolveRevision(plumbing.Revision(revision))
fmt.Println(h.String())
```

**Comment by andreas-kupries** [comment]
Addressed comment about `ResolveRevision`. That works very well.
Commit 10eea5100bcb839cfe9e8f36ab67322c4db481ca

**Comment by enrichman** [comment]
Ah, nice! Much better now! :rocket:

**Review by enrichman — APPROVED** [review]

**Comment by andreas-kupries** [comment]
Actually now. As you can see the CI failed. Investigating I see errors like

```
  {"errors":[{"status":500,"title":"couldn't find remote ref \"refs/heads/master\"","details":"cloning the git repository: https://github.com/epinio/example-wordpress\nServer Backtrace: couldn't find remote ref \"refs/heads/master\""}]}
```

Note the reference to the branch `master`. This is a default value the go package put in. I am currently trying out ways of preventing that.

**Comment by enrichman** [comment]
@andreas-kupries is this issue related?
- https://github.com/go-git/go-git/issues/553

**Comment by andreas-kupries** [comment]
@enrichman 

We actually have here quite a bit of a problem here with the go-git package used by us.

Try to push `--git=https://github.com/epinio/example-wordpress`.
It will fail. The revision is `""`, and that is used as the branch name in the clone, and that branch does not exist.
A revision is needed on epinio's main branch.

This can be overcome, simply do not specify the branch in the `CloneOptions`.
Note however that go-git then goes to use a hardwired default branch name: `master`.
If the repo does not have that the clone will again fail. The `example-wordpress` would serve as exmaple of that still.

I am unclear why the Clone operation needs a branch. There is a flag `NoCheckout` which tells go-git to `No checkout of HEAD after clone if true` ... I had hoped that this would prevent the need for a branch. It does not.

Now, looking again into fixing the handling of commit ids, taking this above into account, the original attempt (a662cd927e9af78fdf5a5b7fd880268744bbacc3) is actually better than the second (10eea5100bcb839cfe9e8f36ab67322c4db481ca).

The original attempt can handle all branch revisions, because that is used with the clone. It fails for commit ids for repos without `master` branch because the clone will fail.

The second attempt actually fails for all revisions if the repo has no `master` branch, because it unconditionally tries to clone with defaults before attending to the revision.

At this point my best bet is to try cloning with `master` and `main` branches as the most popular choices.

I will work more on that that tomorrow.

This PR and ticket are going back to in progress.

**Comment by andreas-kupries** [comment]
This actually looks to be a good place for adding my own questions.

**Comment by andreas-kupries** [comment]
Fresh brain in the morning, I now see that the CloneSpec contains `SingleBranch: true`. Disabling that, and a clone without a branch specified ... works. so this flag is the point where the clone's need for a branch came from.

I can also see the original reasoning for using the flag. It forces the client to clone only the commits needed for that branch. That is a performance optimization which makes the cloning faster. Sensible. I will now rethink the entire code structure to see how much of that optimization can be saved and still have all possible inputs working.

**Comment by andreas-kupries** [comment]
@enrichman 

# Design Notes

## Possible inputs:

  - (A) repository, no revision (empty string)
  - (B) repository, branch name
  - (C) repository, commit id

## Considerations:

  - Correctness
  - Cloning performance

The go-git cloning function has two attributes influencing performance

  - `Depth` specifies the depth towards which to clone.
  - `SingleBranch` specifies the sole branch to check out.

The second flag comes with a problem. Using it __demands__ a branch.  And whatever is found in the `ReferenceName` of the CloneOptions is used.  Even if it is an empty string. And leaving it completely unspecified makes the package use a hardwired default (`master`).

If we have a revision which is a branch name, then we can (try to) use `SingleBranch`. Note however, that we cannot syntactically distinguish branch names from commit ids.

## Solutions

The simplest code handling everything would be

```
Clone (Depth=1)
if revision:
    hash = ResolveRevision (revision)
    Checkout (hash)
```

with no `SingleBranch` in sight, just `Depth`.

More complex, hopefully more performant would be

```
 1:  if not revision:
 2:      Clone (Depth=1)                        // (A)
 3:  else
 4:      Clone (Depth=1,SingleBranch=revision)  // (B,C?)
 5:      if ok: done                            // (B!)
 7:      Clone (Depth=1)                        // (C)
 8:      hash = ResolveRevision (revision)
 9:      Checkout (hash)
```

I.e. try to use a revision as branch name first, to get the `SingleBranch` optimization. When that fails fall back to regular cloning and checkout.  This fall back should happen only for (C).

## Decision

Tending towards the second. While more complex IMHO not overly so.

**Comment by enrichman** [comment]
@andreas-kupries yes, it looks good to me.

As you said the added complexity is not much, and I think that usually you go with the branch name instead of the commit hash.

**Comment by andreas-kupries** [comment]
> ... I think that usually you go with the branch name instead of the commit hash.

My thoughts as well, that (C) is the unusual case.

Ok. Onward.

File: internal/api/v1/application/importgit.go [hunk 1]
```diff
@@ -94,3 +146,81 @@ func (hc Controller) ImportGit(c *gin.Context) apierror.APIErrors {
...
+
+	// Input B or C: Attempt to treat as B (revision is branch name)
+
+	log.Info("importgit, cloning branch", "url", url, "revision", revision)
+	_, err := branchClone(ctx, gitRepo, url, revision)
+	if err == nil {
+		// Was branch name, done.
+		return nil
+	}
+	if !strings.Contains(err.Error(), `couldn't find remote ref`) || !plumbing.IsHash(revision) {
```
Comment (enrichman) [inline internal/api/v1/application/importgit.go:166]: I guess that we can use the [errors.Is](https://pkg.go.dev/errors#Is) here (https://github.com/go-git/go-git/blob/f0b111ab70e4e90013658b0835929b2083902017/remote.go#L38-L49)

```
if !errors.Is(err, remote.NoMatchingRefSpecError) || !plumbing.IsHash(revision) {
	// Some other error, or the revision does not look like a commit id (C)
	return err
}
```

File: internal/api/v1/application/importgit.go [hunk 2]
```diff
@@ -94,3 +146,81 @@ func (hc Controller) ImportGit(c *gin.Context) apierror.APIErrors {
...
+	repository, err := git.PlainCloneContext(ctx, gitRepo, false, &git.CloneOptions{
+		URL:   url,
+		Depth: 1,
+	})
+	if err != nil {
+		return nil, err
+	}
+
+	return repository, nil
+}
```
Comment (enrichman) [inline internal/api/v1/application/importgit.go:226]: It seems that the only difference are the CloneOptions, and we are not adding more info to the error, so we can just

```go
func branchClone(ctx context.Context, gitRepo, url, revision string) (*git.Repository, error) {
	opts := &git.CloneOptions{
		URL:           url,
		Depth:         1,
		SingleBranch:  true,
		ReferenceName: plumbing.NewBranchReferenceName(revision),
	}
	return git.PlainCloneContext(ctx, gitRepo, false, opts)
}

func generalClone(ctx context.Context, gitRepo, url string) (*git.Repository, error) {
	opts := &git.CloneOptions{
		URL:           url,
		Depth:         1,
	}
	return git.PlainCloneContext(ctx, gitRepo, false, opts)
}
```

**Review by enrichman — CHANGES_REQUESTED** [review]
Just a couple of comments, but it's fine!

File: internal/api/v1/application/importgit.go (hunk 2 above)
Comment (andreas-kupries) [reply internal/api/v1/application/importgit.go:226]: Yes. Missed that.

File: internal/api/v1/application/importgit.go (hunk 1 above)
Comment (andreas-kupries) [reply internal/api/v1/application/importgit.go:166]: Yes, definitely better.

File: internal/api/v1/application/importgit.go (hunk 2 above)
Comment (andreas-kupries) [reply internal/api/v1/application/importgit.go]: Done, commit 91d2efd273b228842207c707fafd5752303327b6

**Review by enrichman — APPROVED** [review]
