### PR TITLE
Fix command completion crashes

### LINKED ISSUE #557: Crash in command completion for `app show`
Seen on branch `main`, commit 14c682e34b0c3c07fc2c2251d2f3cfd3f49dedb8

The command completion for `app show` is not working
An app `hello` was present, and completion did not pick it up.
Trialing the relevant command directly:

```
ep __complete app show h
```

showed a crash.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1292f6a]

goroutine 1 [running]:
golang.org/x/time/rate.(*Limiter).WaitN(0xc00003aa50, 0x0, 0x0, 0x1, 0x0, 0x0)
	/home/work/SUSE/go/pkg/mod/golang.org/x/time@v0.0.0-20201208040808-7e3f01d25324/rate/rate.go:237 +0xba
golang.org/x/time/rate.(*Limiter).Wait(...)
	/home/work/SUSE/go/pkg/mod/golang.org/x/time@v0.0.0-20201208040808-7e3f01d25324/rate/rate.go:219
k8s.io/client-go/util/flowcontrol.(*tokenBucketRateLimiter).Wait(0xc000736ee0, 0x0, 0x0, 0xc0000f2988, 0x0)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/util/flowcontrol/throttle.go:106 +0x4b
k8s.io/client-go/rest.(*Request).tryThrottle(0xc0008f6000, 0x0, 0x0, 0xabcb2c, 0xc0006bd200)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/request.go:587 +0xa4
k8s.io/client-go/rest.(*Request).request(0xc0008f6000, 0x0, 0x0, 0xc0000f2ee8, 0x0, 0x0)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/request.go:860 +0x29d
k8s.io/client-go/rest.(*Request).Do(0xc0008f6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/request.go:964 +0xe0
k8s.io/client-go/kubernetes/typed/core/v1.(*nodes).List(0xc00012f0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/kubernetes/typed/core/v1/node.go:88 +0x19a
github.com/epinio/epinio/helpers/kubernetes/platform/kind.(*kind).Detect(0xc000466360, 0x0, 0x0, 0xc000458000, 0x0)
	/home/work/SUSE/dev/epinio/helpers/kubernetes/platform/kind/kind.go:25 +0xac
github.com/epinio/epinio/helpers/kubernetes.(*Cluster).detectPlatform(0xc000721c80, 0x0, 0x0)
	/home/work/SUSE/dev/epinio/helpers/kubernetes/cluster.go:127 +0x92
github.com/epinio/epinio/helpers/kubernetes.GetCluster(0x0, 0x0, 0x0, 0x6, 0xc000686ac0)
	/home/work/SUSE/dev/epinio/helpers/kubernetes/cluster.go:106 +0x105
github.com/epinio/epinio/internal/cli/clients.NewEpinioClient(0x0, 0x0, 0xc0000e1900, 0x0, 0x0, 0x0)
	/home/work/SUSE/dev/epinio/internal/cli/clients/client.go:68 +0x60
```

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fix #557 

A `nil`-valued `cmd.Context()` result in cobra `ValidArgsFunction` broke command completion across the board.
Use `context.Background()` instead.

### CODE REVIEW

File: internal/cli/apps.go [hunk 1]
```diff
@@ -90,12 +92,12 @@ var CmdAppCreate = &cobra.Command{
 			return nil, cobra.ShellCompDirectiveNoFileComp
 		}
 
-		app, err := clients.NewEpinioClient(cmd.Context())
+		app, err := clients.NewEpinioClient(context.Background())
```
Comment (jimmykarily) [inline internal/cli/apps.go:95]: Some of these auto-completion functions take quite long to complete. Maybe we could create one context with Timeout (https://pkg.go.dev/context#WithTimeout) at the beginning and use it in all commands.

Comment (andreas-kupries) [reply internal/cli/apps.go:95]: I would consider that to be out of scope for this bug fix. IMHO better done as a separate ticket.

**Comment by andreas-kupries** [comment]
Passed local acceptance tests.

**Review by jimmykarily — APPROVED** [review]
