### PR TITLE
Remodeled service responses

### LINKED ISSUE #981: Services returned by list differ from those when fetched directly
**Describe the bug**
The response when fetching services by list is different from that when directly fetching a service. Ideally they should both match and return the same data (including the key-value service data)

This does currently cause an issue in the UI when refreshing on service detail page (we fetch the specific service and it doesn't contain the required data to show the service info) - https://github.com/epinio/ui/issues/45. It also means the user cannot edit their service's key-value pairs (they're not present from the list https://github.com/epinio/ui/issues/46)

**To Reproduce**
Fetch service lists via `/api/v1/namespaces/<ns>/services` or `/api/v1/services` and service is
```
{"meta":{"name":"aaaaaa","namespace":"dev"},"boundapps":null}
```
vs `/api/v1/namespaces/<ns>/services/<service name>`
```
{"user":"my-epinio-user","details":{"a":"a"}}
```
**Desktop/CLI (please complete the following information):**
 - Epinio Version: 0.1.6

### PR DESCRIPTION
**Pull request by andreas-kupries**
Fixes #981

### CODE REVIEW

File: internal/api/v1/service/show.go [hunk 1]
```diff
@@ -40,19 +40,25 @@ func (sc Controller) Show(c *gin.Context) apierror.APIErrors {
 		}
 	}
 
+	appsOf, err := servicesToApps(ctx, cluster, namespace)
```
Comment (jimmykarily) [inline internal/api/v1/service/show.go:43]: There are various ways to improve performance and complexity here. I think this method shouldn't list all apps like it does now. It doesn't need the fully populated applications (which is fetches by calling `application.List`). It only needs the app to service binding information. This information can be extracted by simply fetching all the "binding" secrets (those created like this: https://github.com/epinio/epinio/blob/main/internal/application/services.go#L154-L159).

Fetching just those secrets should be cheaper than fetching all apps (fully populated).

Comment (jimmykarily) [reply internal/api/v1/service/show.go:43]: Consumers of servicesToApps seem to only need the app names, should be ok to not having the full app objects.

Comment (jimmykarily) [reply internal/api/v1/service/show.go:43]: from what I see, we would need some additional label on the `*-svc` secrets to filter them from `*-env` and `*-scale` ones.

Comment (andreas-kupries) [reply internal/api/v1/service/show.go:43]: I will have a look. The `servicesToApps` as is is certainly becoming more of a bottle neck, with its extended use. And the fact that fetching an app is pulling more data now than it was at the beginning.

Comment (andreas-kupries) [reply internal/api/v1/service/show.go:43]: I am actually not sure about the `binding secrets` ... These secrets existed for catalog services, where they were separate from the service secret itself. What we have now are only `custom services`, and for these we should not have separate binding secrets at all. As these services' secrets contain the credentials directly apps can mount them as they are.

The name/part-of labels in the referenced code look to be wrong.

I will definitely check in this area now.

That said ... Even if we do not have binding secrets at the moment, adding them to the system might be a good idea, as they are indeed make it possible to query the app/service binding in any direction without having to look into a specific (app -> service) or all applications (service -> app). You could directly select for the desired set (all for a service, all for an app, all  - last for index endpoints to use one call for everything and scatter the info, instead one per app or service).

Comment (andreas-kupries) [reply internal/api/v1/service/show.go:43]: Aha ... The referenced code is about the application-associated secret containing the names of desired services of that app ... Which is indeed the bound services of the app, outside of the app pod ... 

So, yes, your (@jimmykarily ) idea of simply reading all these has very much merit. That said, I was correct in saying that these are not the binding secrets as we had for catalog services.

That was a good catch. These secrets sort of floated in my mind and never connected that they contain the same binding information we pull(ed) from the app pods.

Comment (andreas-kupries) [reply internal/api/v1/service/show.go:43]: Additional label for filtering ... Likely yes. Will check if there is a common labels we can use, beyond what is already present.

File: pkg/api/core/v1/models/models.go [hunk 2]
```diff
@@ -24,8 +24,8 @@ type ServiceRef struct {
 
 // ServiceResponse represents the data of a single service instance
 type ServiceResponse struct {
-	Meta      ServiceRef `json:"meta"`
-	BoundApps []string   `json:"boundapps"`
+	Meta ServiceRef          `json:"meta"`
+	Spec ServiceShowResponse `json:"spec"`
```
Comment (richard-cox) [inline pkg/api/core/v1/models/models.go:28]: Minor comment, the response to apps contains spec like details in a `configuration` property. For conformity could they use the same name?

App Response
```
{
        "configuration": {
            "environment": {},
            "instances": 1,
            "routes": [
                "from-archive.192.168.0.2.omg.howdoi.website"
            ],
            "services": [
                "db-service-2"
            ]
        },
        "deployment": {
...
        },
        "meta": {
...
        },
        "status": "running",
        "statusmessage": ""
    }
```

Comment (andreas-kupries) [reply pkg/api/core/v1/models/models.go:28]: Ah, you want current `Spec` to be called `Configuration`, right ? If so, trivial change, no problem.

Comment (richard-cox) [reply pkg/api/core/v1/models/models.go:28]: @andreas-kupries :+1:

Comment (andreas-kupries) [reply pkg/api/core/v1/models/models.go]: commit 5853e2ec8dcda5a7a150f41d1d494db5ee39f3ea

File: internal/api/v1/service/show.go (hunk 1 above)
Comment (andreas-kupries) [reply internal/api/v1/service/show.go]: commit 04467923e1d9550b60517a9f998f673c01fbf356

File: internal/application/services.go [hunk 3]
```diff
@@ -15,6 +17,173 @@ import (
...
+		for _, binding := range appBindings.Items {
+			appName := binding.ObjectMeta.Labels["app.kubernetes.io/name"]
+			namespace := binding.ObjectMeta.Labels["app.kubernetes.io/part-of"]
+
+			for serviceName := range binding.Data {
+				key := ServiceKey(serviceName, namespace)
+				result[key] = append(result[key], appName)
+			}
+		}
+	} else {
```
Comment (jimmykarily) [inline internal/application/services.go:158]: Is there a reason why we can't always use a key that has the namespace in? I mean, even if the caller asked only for services of one namespace, it obviously has that namespace at hand and can construct a key for each service to look it up. It would make this code but also the caller simpler if the result of this method was consistent.

File: internal/application/services.go [hunk 4]
```diff
@@ -15,6 +17,173 @@ import (
...
+
+	bindings, err := BoundAppsNames(ctx, cluster, namespace)
+	if err != nil {
+		return result, err
+	}
+
+	// Internal map of fetched applications.
+	fetched := map[string]*models.App{}
+
+	if namespace == "" {
```
Comment (jimmykarily) [inline internal/application/services.go:36]: this if/else won't be needed if with the suggested refactoring here: https://github.com/epinio/epinio/pull/1014/files#r756052176

File: internal/application/services.go (hunk 3 above)
Comment (andreas-kupries) [reply internal/application/services.go:158]: True. Time spent in encoding/decoding keys should be small. Will do.

Comment (andreas-kupries) [reply internal/application/services.go]: commit 858aeddc147ade02f2e1c91012b1809ac3f6989a

File: internal/application/services.go (hunk 4 above)
Comment (andreas-kupries) [reply internal/application/services.go]: commit 858aeddc147ade02f2e1c91012b1809ac3f6989a

File: internal/application/services.go [hunk 5]
```diff
@@ -15,6 +17,133 @@ import (
...
+			}
+		}
+	}
+
+	return result, nil
+}
+
+// BoundAppsNames returns a map from the service names of services in the specified namespace,
+// to the names of the applications they are bound to. For an empty namespace the map
+// contains the services in all namespaces, and the keys are a combination of namespace
```
Comment (jimmykarily) [inline internal/application/services.go:96]: Update comment? (now it's always a combination of name and namespace)

Comment (andreas-kupries) [reply internal/application/services.go:96]: Right. Just a moment.

Comment (andreas-kupries) [reply internal/application/services.go]: commit 2903a9968e0a1a0ad8c2859cad9275f7ab96551b

**Review by jimmykarily — APPROVED** [review]
