### PR TITLE
Ignore services that were deleted in the middle of an "index" request

### LINKED ISSUE #1235: Don't fail when a service is removed in the middle of a request

### PR DESCRIPTION
**Pull request by jimmykarily**
Fixes #1235 

E.g. This happens in tests when a ginkgo node is listing all services
from all namespaces while some other ginkgo node is deleting a service
in that list. Our "index" code, first fetchese the list of services and
then finds details for each one of them. If a service is gone between
listing and fetching the details, the old version would make the whole
request fails. Now the service is simply ignored.

### CODE REVIEW

File: internal/api/v1/service/index.go [hunk 1]
```diff
@@ -56,10 +57,13 @@ func makeResponse(ctx context.Context, appsOf map[string][]string, services serv
 	response := models.ServiceResponseList{}
 
 	for _, service := range services {
-
 		serviceDetails, err := service.Details(ctx)
 		if err != nil {
-			return models.ServiceResponseList{}, err
+			if apierrors.IsNotFound(err) {
```
Comment (enrichman) [inline internal/api/v1/service/index.go:62]: You can keep it together and avoid the `continue`

```golang
if err != nil && !apierrors.IsNotFound(err){
    return models.ServiceResponseList{}, err
}
```

Comment (jimmykarily) [reply internal/api/v1/service/index.go:62]: good one, fixing

Comment (jimmykarily) [reply internal/api/v1/service/index.go:62]: Hm, I need the continue because I don't want the rest of the code in this block to run

Comment (enrichman) [reply internal/api/v1/service/index.go:62]: Ah, I haven't see the rest of the block. Then it's fine :+1:

**Review by enrichman — APPROVED** [review]
