### PR TITLE
Fix for windows paths

### LINKED ISSUE #1101: AKS-CI is failing
The AKS-CI test is failing during app deployment with this error:
```
Deploying application ...
  2022/01/09 03:47:00 EpinioApiClient "msg"="response is not StatusOK" "error"="Internal Server Error: invalid character 'a' in string escape code" "status"=500 
  error pushing app to server: can't deploy app: Internal Server Error: invalid character 'a' in string escape code
```

For example see this test: https://github.com/epinio/epinio/runs/4751235189?check_suite_focus=true

I was not able to reproduce the issue with manual test on Linux client as well as CI installation test running on a linux client. The CI test runs on a Windows client, maybe something is not exported correctly by Epinio which could explain this error?

### PR DESCRIPTION
**Pull request by enrichman**
This should fix #1101 

I've also removed a couple of possible panics (if the `err` is nil then the `apierror.InternalError` will panic).

### CODE REVIEW

File: internal/application/origin_test.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
+package application
+
+import (
+	"reflect"
+	"testing"
+
+	"github.com/epinio/epinio/pkg/api/core/v1/models"
+)
+
+func Test_buildBodyPatch(t *testing.T) {
```
Comment (jimmykarily) [inline internal/application/origin_test.go:10]: I'm not sure our make target will run non-ginkgo tests: https://github.com/epinio/epinio/blob/main/Makefile#L71-L72

Also, although this is just a unit test, I would still stick to ginkgo syntax for consistency. E.g. like this one: https://github.com/epinio/epinio/blob/main/internal/s3manager/s3manager_test.go

I find the tests descriptions helpful when trying to understand what is being tested.

File: internal/application/origin.go [hunk 2]
```diff
@@ -110,31 +113,58 @@ func SetOrigin(ctx context.Context, cluster *kubernetes.Cluster, app models.AppR
...
 		}
-		value = fmt.Sprintf(`"git": {%s}`, value)
 	}
 
-	// And enter into the app
-	patch := fmt.Sprintf(`[{"op": "replace", "path": "/spec/origin", "value": {%s}}]`, value)
+	operations := []PatchOperation{{
+		Op:    "replace",
+		Path:  "/spec/origin",
+		Value: patchOpValue,
```
Comment (andreas-kupries) [inline internal/application/origin.go:149]: Hm ... `patchOpValue` is the same type as `origin`, right ?
Could we use `origin` directly here ?
The preceding lines are effectively a more complicated `patchOpValue := origin` also ?! I.e could be dropped ?!

Comment (andreas-kupries) [reply internal/application/origin.go:149]: Oh, I see now. You created a local copy of the model type, and all the code above is doing the copying.
Does the local copy have a different tagging for json marhsalling ? ...
Yes, the `Kind` field is not present in the local copy.
Ok then, retracting my thoughts above.

**Review by andreas-kupries — APPROVED** [review]
You can resolve my comments without action ... Or maybe add some comments giving an overview of your solution ;)

File: internal/application/origin.go (hunk 2 above)
Comment (enrichman) [reply internal/application/origin.go:149]: Yes, I was thinking to use the same but unfortunately the GitOrigin is slightly different (`repository` vs `url`), not sure why.

Comment (andreas-kupries) [reply internal/application/origin.go:149]: Please bring it up in the planning. I would like to have the code simple(r) here.
It may affect the server API, i.e. IIRC the model goes over the wire between client and server.
So a change would also affect @richard-cox

Comment (enrichman) [reply internal/application/origin.go:149]: As discussed I'm going to change the GitRef struct model to match the CRD

https://github.com/epinio/epinio/blob/dfc3aba919800f30a6a263949b9e7a813177359e/pkg/api/core/v1/models/app.go#L20-L23

https://github.com/epinio/helm-charts/blob/a3d66d6c0dda2d8c5752247f93a3e3fdf79064ec/chart/epinio/templates/app-crd.yaml#L59-L67

to

```golang
type GitRef struct {
	Revision   string `json:"revision,omitempty" yaml:"revision,omitempty"`
	Repository string `json:"repository"         yaml:"repository"`
}
```

I am going to update also the yaml, is that fine?

Comment (andreas-kupries) [reply internal/application/origin.go:149]: I am not sure right now ... The yaml may have to match the CRD spec. I would not touch it, in the interest of making a minimal change to get the desired effect.

Note that you only have to change the `json:"url"` to ``json:"repository"`.
There is no need to change the field name in Go.
I.e. the `URL` to `repository` change is superfluous as well.

Comment (enrichman) [reply internal/application/origin.go:149]: Ok, let's keep it at the minimum then. :)

**Comment by andreas-kupries** [comment]
Note that we generally rebase the branch to the new head of main, instead of merging main into the branch.

**Comment by enrichman** [comment]
Finally green :green_circle:

File: pkg/api/core/v1/models/models.go [hunk 3]
```diff
@@ -90,10 +90,10 @@ type ApplicationStage struct {
 // ApplicationOrigin is the part of the manifest describing the origin of the application
 // (sources). At most one of the fields may be specified / not empty.
 type ApplicationOrigin struct {
-	Kind      int    `yaml:"-"` // Hidden from yaml. Type tag to simplify struct usage.
-	Container string `yaml:"container,omitempty"`
-	Git       GitRef `yaml:"git,omitempty"`
-	Path      string `yaml:"path,omitempty"`
+	Kind      int     `                           yaml:"-" ` // Hidden from json and yaml. Type tag to simplify struct usage.
```
Comment (andreas-kupries) [inline pkg/api/core/v1/models/models.go:93]: Is this indeed hidden from JSON without a `json:"-"` clause ?

**Review by andreas-kupries — CHANGES_REQUESTED** [review]
Have a question

File: pkg/api/core/v1/models/models.go (hunk 3 above)
Comment (enrichman) [reply pkg/api/core/v1/models/models.go:93]: Ah, I left the comment. I had to remove the `json:"-"` because it was actually used to marshal/unmarshal the Kind.

I don't really like to expose the property as-is

```
{
    "Kind": 1,
    "path": "C:\\Documents\\app"
}
```

but change it in other ways would need a bit of refactor. What do you think?

The best would be to have something like an enum mapping the Kind `int`, so exposing something more explicit:

```
{
    "type": "ORIGIN_PATH",
    "path": "C:\\Documents\\app"
}
```

Comment (andreas-kupries) [reply pkg/api/core/v1/models/models.go:93]: That is weird wrt `json:"-"`. This is, AFAIK the proper way for excluding the field from (un)marshalling.

Looking at the tests you have I see that you have `Kind` in the JSON. That is what I am expecting for this tagging, without the `json:"-"` clause. Are you saying that when you add this clause the tests still pass, with `Kind` in the JSON ?

Go has no enums as we are used from C. See https://github.com/epinio/epinio/blob/5f3872d1e3c5eca11937f6020d459f8129502542/pkg/api/core/v1/models/models.go#L100-L105 for an example of a Go enum.

Comment (enrichman) [reply pkg/api/core/v1/models/models.go:93]: No, I meant that originally I have added the clause but other tests were failing, because they were implicitly relying on the `Kind` field.
So I had to remove it and keep the marshaling as is (with the `Kind` exposed).

I know about the enum, unfortunately (is a feature that I actually miss). To add this kind of behaviour the only way would be to add a custom type/struct and implement the `Unmarshal` interface I suppose.
Probably overkill.

Comment (andreas-kupries) [reply pkg/api/core/v1/models/models.go:93]: Oh. I see. ... Were the failing tests API tests ? Because IIRC it is exposed there. Makes the handling on each side nicer (albeit opens each side up to getting structure where kind and actual actual information do not match).

We could drop it from the API, close that attack vector ... Not in this issue and PR.

Comment (andreas-kupries) [reply pkg/api/core/v1/models/models.go:93]: I recommend adding a note in the code about this issue with Kind not hidden.

Resolving as ok, will approve.

**Review by andreas-kupries — APPROVED** [review]

**Review by andreas-kupries — APPROVED** [review]
