### PR TITLE
Use same loadbalancer error message in both checks

### LINKED ISSUE #187: Check for external load balancer before installation
`carrier install` fails on minikube without metallb (as described [here](https://github.com/SUSE/carrier/blob/main/docs/install.md))

Carrier should add a check for metallb (on minikube) to warn users (resp. just install metallb)

### PR DESCRIPTION
**Pull request by manno**
fixes #187

### CODE REVIEW

File: deployments/traefik.go [hunk 1]
```diff
@@ -27,9 +27,13 @@ type Traefik struct {
...
 
 const (
-	TraefikDeploymentID = "traefik"
-	traefikVersion      = "9.11.0"
-	traefikChartURL     = "https://helm.traefik.io/traefik/traefik-9.11.0.tgz"
+	TraefikDeploymentID   = "traefik"
+	traefikVersion        = "9.11.0"
+	traefikChartURL       = "https://helm.traefik.io/traefik/traefik-9.11.0.tgz"
+	MessageLoadbalancerIP = "timed out waiting for LoadBalancer IP on traefik service\n" +
+		"Ensure your kubernetes platform has the ability to provision LoadBalancer IP address.\n\n" +
```
Comment (andreas-kupries) [inline deployments/traefik.go:34]:
```suggestion
		"Ensure your kubernetes platform has the ability to provision a LoadBalancer IP address.\n\n" +
```

**Review by andreas-kupries — CHANGES_REQUESTED** [review]
Just a small nit in the syntax

**Review by andreas-kupries — APPROVED** [review]
